#! /usr/local/bin/lua
-- Denfile for Hello World 1.4

-- Import the Ursa library
require "luarocks.loader"
require "ursa"

-- List our source files
local libpng_cflags = ursa.util.system("pkg-config libpng --cflags")
local libpng_linkflags = ursa.util.system("pkg-config libpng --libs")

local sources = {"main", "ui", "debug", "log", "driver_vga", "driver_console", "driver_x"}

local objects = {}
for _, file in ipairs(sources) do
  ursa.rule{file .. ".o", file .. ".cpp", ("g++ -o %s.o -c %s.cpp %s"):format(file, file, libpng_cflags)}
  table.insert(objects, file .. ".o")
end
 
ursa.rule{"hello.exe", objects, ("g++ -o hello.exe %s %s"):format(table.concat(objects, " "), libpng_linkflags)}
 
ursa.command{ursa.command.default, "hello.exe"}
ursa.command{"run", "hello.exe", "./hello.exe"}

ursa.build{...}
